---
title: "Untitled"
author: "Stephanie, Noah"
date: "3/26/2018"
output: html_document
---

```{r setup, include=FALSE}
library(install.load)
install_load('networkD3')
install_load('R.matlab')
install_load('ggplot2')
```

## R Markdown


```{r}

#sn_startdate <- readMat("")


loc <- readMat("data/withdate.mat")
#1st column
val <- loc[["withdate"]][[1]][,1]
val <- as.POSIXct((val - 719529)*86400, origin = "1970-01-01")

#create data frame with date and location
date_location <- data.frame(val,loc[["withdate"]][[1]][,2])
colnames(date_location) <- c("date","location")
home <- 5119.40811000000
date_location$location[date_location$location == home] <- "Home"
#get day of the week in new column
date_location$days <- weekdays(as.Date(date_location$date))
date_location$time <- as.numeric(format(date_location$date,"%H"))
when_home <- dplyr::filter(date_location, date_location$location == "Home")
a <- ggplot(when_home, aes(days,time)) + geom_point(alpha=.2) + scale_x_discrete(limits=c("Sunday","Monday","Tuesday","Wednesday","Thursday", "Friday","Saturday"))
a

#start w/ values of hour greater than 8
when_home8 <- dplyr::filter(when_home, when_home$time > 8)
b <- ggplot(when_home8, aes(days,time)) + geom_point(alpha=0.5) + scale_x_discrete(limits=c("Sunday","Monday","Tuesday","Wednesday","Thursday", "Friday","Saturday"))
b

```

```{r}
loc2 <- readMat("/Users/stephanierivera/Documents/MATLAB/places.mat")
```

